# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kZ+R3ISz6AArN67ZVBeLljb5Fff1Qh4PSKaqT1ELo4DWRkST3KqOEzNN09+udFkgodfGqQJa8IL114v3e0lA5saMDkV3Mm0hQTVAKnRm99ZxTkb9ku5397vgiIH2g+z4S9DZbb5/cJGGjvRV0sL5Inusr9WAnTK0bxDJAtFO5QyLhtMX3mEnYvYKnuzcnvcdpJ+IRsjzAbRA3BuFjmKQDCd3ukd7Y49SlmQ7eGEWl+erDfAQN3lzEtVTso8n4XOmgM/Zh0UTG458NU1amNgiE+Wh0qtgV5aKXVLzklHyAGT7T58hakzWbb+nU0k+JSYfuSRWQk0hR5jrIBEp3+utpcQoDxtfJcX8U+LmlnRD3Dpqwl0n6YBTBlExbHrvgirZcnl6MqbFpEaEdD0+zuplci62scxZ/Egz+mG7pBvHmVYNqnwgOvuAIPa0SCwVZuxXcBURcvY0OpQGjDHi4olVA64BVGi14+ljBgS2G1Djekm2AkLmfQb3yLRdiqTpHFJwymFn9ynmHukFvv/X8biQjQUni6YzcV6EvnXKtiJOg3VR8e7OZUzNOsYXO2nj7lT/AwhfUWjUlrqQtgVRrmxaznT6eGIH9RMCSoG+otobHwThBw9V5VI01C4yAJ05GrGTYz+QO0mtApFer1twAN6vDeAPKi4FrBEW0yh5DYygeM8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
