# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UzDQfZ2PH1Um4qsnDmxWOOd7tL3AqoWrVp0c7fAe/ZmUTIYo1SsKdePJw4lBlBmxA/40SJToc5hHsfCgCS1Kqz6qKw15kJif5JHxLchQm05UxqmhbHTbGBlk8Yii64osUVQI7F8D2hKqqCoPV6QuNpJWKb2VAgDKpdD8jjGc9FwR6p+zh4c2cqQMy7Ym0noM3LNbOyNLDzXRF9aubWaz/AvpnOpHJfLQN4J7NQ8XzcMJPN5tjcNrYxpbiMxNnDFMUC0wbdd5Cp2dbm49cJ8I8jut8BXGKsmdBly6dTBs6ICErbsxMtnEQMiMnSf3WQMoksSgEZoTiGXc3C809TtN3PPyseTV/xdS30qrAXnTl62t1Vqmn38kuyZZP34lfM/juYD2SIamLsS+xkB/DTHNluD00VNVlAgnmGj7uj48KGV4HpYXTntoeknpUmQDBNbDCl1bMKqPPiOb4jO4B/CGMDEIgol7+6e4UnhpyKtHFPf4p2Xr/bgfeIyo2cS6kFVf0Awqjr2b8jOMMOFbZC79G0pMfvE5MJP2SRe83ohHgQ0TsGgItMGXZTy0Cz/KIrOPuW9yjZV/qGr9d8B5+ovNPTnCnMdR1zEo3HypNTZHlNtqTbJxPYdj1W+HSA0iVdkC/Fr4cnn436RnLoyaDycmHQCLLKOwe43KPYwMFVo19Ro="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
