travis:
  secure:
    BINSTAR_TOKEN: dOYUUQpsnEJjG/bo2fKIAdNhZP1ncAVq/60PosvyjE/RkHDsE0fTaQxsXA4v8A4+JpkST8AtyerrXtBVoFHWOefTnEM+P/Hc4SEeyAjA2uqO6QwY3QwG7JWk+13sgsTT1KsYlWUWNOkT6k3gbzinldlMCkJ0XK+47ZpwQSTjOzRxc6TkJxrRw4s/AdFkXGfgMHG76y5XN4dqNJVzgJkzRjm2H/9/56kVkUypWvWKETPdo9CxhXvWC7Xo/eEwQFPzgk7dUoXQCOOpCVeDqLsEJCoDSaLasQRPNONJsggbG9dB68eHnLdX6sHYDA85J/TcN6EwKQPhmcZISkQ/GQKryqgYDiN8m1k5+FyKwjCZ/stI2pf6GHv1HGRjORnkYIH2hsfRMvov7V8LXFruWTRoVj6rANWazPnPXLPEW4+16JovWK1l9uXrNmZr3c+G3xtd4jeImPfb5sTsqMMXwIEHH53KBEo0KO9dD6kKMaZ8x5iT0Ibvp6OWUdSczqY2InjOLuC0EQ/2zfSYHoGkG83hnd1/0hedLJgaGg5GngV6fUL87aqAjfNW6mPYOcQ64iH3PnNMaQV8Xgsz54asBoWa4ZSxMFUNyuZAMuV0bough7NpAnky1nzH1Om/nCs2NAGweYIJpfHdl1OlkJ0wdh2anNf8/htQ6FIky9d9qeBSvn0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
