travis:
  secure:
    BINSTAR_TOKEN: kZ+R3ISz6AArN67ZVBeLljb5Fff1Qh4PSKaqT1ELo4DWRkST3KqOEzNN09+udFkgodfGqQJa8IL114v3e0lA5saMDkV3Mm0hQTVAKnRm99ZxTkb9ku5397vgiIH2g+z4S9DZbb5/cJGGjvRV0sL5Inusr9WAnTK0bxDJAtFO5QyLhtMX3mEnYvYKnuzcnvcdpJ+IRsjzAbRA3BuFjmKQDCd3ukd7Y49SlmQ7eGEWl+erDfAQN3lzEtVTso8n4XOmgM/Zh0UTG458NU1amNgiE+Wh0qtgV5aKXVLzklHyAGT7T58hakzWbb+nU0k+JSYfuSRWQk0hR5jrIBEp3+utpcQoDxtfJcX8U+LmlnRD3Dpqwl0n6YBTBlExbHrvgirZcnl6MqbFpEaEdD0+zuplci62scxZ/Egz+mG7pBvHmVYNqnwgOvuAIPa0SCwVZuxXcBURcvY0OpQGjDHi4olVA64BVGi14+ljBgS2G1Djekm2AkLmfQb3yLRdiqTpHFJwymFn9ynmHukFvv/X8biQjQUni6YzcV6EvnXKtiJOg3VR8e7OZUzNOsYXO2nj7lT/AwhfUWjUlrqQtgVRrmxaznT6eGIH9RMCSoG+otobHwThBw9V5VI01C4yAJ05GrGTYz+QO0mtApFer1twAN6vDeAPKi4FrBEW0yh5DYygeM8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
